# https://github.com/alacritty/alacritty-theme
general.import = [
# dark
#"~/github_repos/alacritty-theme/themes/xterm.toml"
#"~/github_repos/alacritty-theme/themes/cyber_punk_neon.toml"
#"~/github_repos/alacritty-theme/themes/baitong.toml"
#"~/github_repos/alacritty-theme/themes/github_dark_high_contrast.toml"
#"~/github_repos/alacritty-theme/themes/ubuntu.toml"
#"~/github_repos/alacritty-theme/themes/aura.toml"
#"~/github_repos/alacritty-theme/themes/ayu_dark.toml"
"~/github_repos/alacritty-theme/themes/blood_moon.toml"
# light
#"~/github_repos/alacritty-theme/themes/github_light_high_contrast.toml"
#"~/github_repos/alacritty-theme/themes/solarized_light.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "Source Code Pro"

[window]
opacity = 0.94
