# https://github.com/alacritty/alacritty-theme
general.import = [
# dark
#"~/.config/alacritty/themes/themes/xterm.toml"
#"~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
#"~/.config/alacritty/themes/themes/baitong.toml"
#"~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
#"~/.config/alacritty/themes/themes/ubuntu.toml"
#"~/.config/alacritty/themes/themes/aura.toml"
#"~/.config/alacritty/themes/themes/ayu_dark.toml"
"~/.config/alacritty/themes/themes/blood_moon.toml"
# light
#"~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
#"~/.config/alacritty/themes/themes/solarized_light.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "Source Code Pro"

[window]
opacity = 0.94
